_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 8
lr:
    value: 0.001
num_epochs:
    value: 100
